name: Trigger deployment

on:
  push:
    branches:
      - main

jobs:
  sbt-run-backend:
    runs-on: self-hosted
    steps:
      - name: Send HTTP request to invoke redeployment
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '["https://control.felixberg.dev/redeploy/logicbox"]'
          expected: '[200]'
