name: Mirror full repo to private

on:
  push:
    branches:
      - "**"
  delete:
    branches:
      - "**"
  create:
    branches:
      - "**"
  schedule:
    - cron: "0 * * * *" # Optional: hourly mirror
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important: fetch full history for mirror

      - name: Push mirror to private repo
        env:
          GIT_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add mirror https://x-access-token:${GIT_TOKEN}@github.com/kasperskovhansen/logicbox-mirror.git
          git remote -v
          git push --mirror mirror || (echo "Push failed" && exit 1)
