name: SBT build to docker

on:
  push:
    branches:
      - main

jobs:
  sbt-docker-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '8'

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Run sbt docker:stage
        run: cd backend && sbt docker:stage
        
      - name: Push to deployment branch
        run: |
          git config --global user.name "Logicontainer GitHub Actions"
          git config --global user.email "blah@blooe.bloop"
          git checkout -B deployment-be
          git add .
          git commit -m "Automated deployment build from main"
          git push origin deployment-be --force
